#!/usr/bin/env node

import fs from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';

const ROOT = process.cwd();
const ITCH_DIR = path.join(ROOT, 'assets', 'itch');
const PUBLIC_THIRD_PARTY_DIR = path.join(ROOT, 'public', 'assets', 'third_party');
const OVERRIDES_JSON_PATH = path.join(ITCH_DIR, 'asset-overrides.json');
const ATTRIBUTION_JSON_PATH = path.join(ITCH_DIR, 'attribution.json');
const CATALOG_PATH = path.join(ITCH_DIR, 'free-game-assets.json');
const OVERRIDES_TS_PATH = path.join(ROOT, 'src', 'data', 'assetOverrides.ts');
const PROTECTED_KEYS = new Set([
  'player',
  'zombie',
  'runner',
  'tank',
  'ranged',
  'exploder',
  'healer',
  'stealth',
  'elite',
  'boss_tyrant',
  'boss_necro',
  'boss_devourer',
  'zone_city_tile',
  'zone_wasteland_tile',
  'zone_industry_tile',
  'zone_road_tile',
]);

function parseArgs(argv) {
  const args = { _: [] };
  for (let i = 0; i < argv.length; i += 1) {
    const token = argv[i];
    if (!token.startsWith('--')) {
      args._.push(token);
      continue;
    }
    const key = token.slice(2);
    const value = argv[i + 1];
    if (!value || value.startsWith('--')) {
      args[key] = true;
      continue;
    }
    args[key] = value;
    i += 1;
  }
  return args;
}

function decodeXmlText(value) {
  if (!value) return '';
  return value
    .replaceAll('&amp;', '&')
    .replaceAll('&lt;', '<')
    .replaceAll('&gt;', '>')
    .replaceAll('&quot;', '"')
    .replaceAll('&#39;', "'");
}

function readTag(xml, tag) {
  const match = xml.match(new RegExp(`<${tag}>([\\s\\S]*?)<\\/${tag}>`, 'i'));
  return decodeXmlText(match?.[1]?.trim() ?? '');
}

function toSafeSlug(value) {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9_-]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function parseMap(value) {
  const entries = [];
  for (const item of value.split(',')) {
    const raw = item.trim();
    if (!raw) continue;
    const [key, relativePath] = raw.split('=').map((s) => s.trim());
    if (!key || !relativePath) {
      throw new Error(`--map 格式错误: ${raw}，应为 key=file.png`);
    }
    entries.push({ key, relativePath });
  }
  if (entries.length === 0) {
    throw new Error('未提供有效的 --map 映射');
  }
  return entries;
}

function toPosix(inputPath) {
  return inputPath.split(path.sep).join('/');
}

async function ensureParentDir(filePath) {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
}

async function readJson(filePath, fallback) {
  if (!existsSync(filePath)) return fallback;
  const text = await fs.readFile(filePath, 'utf8');
  try {
    return JSON.parse(text);
  } catch {
    return fallback;
  }
}

async function writeJson(filePath, value) {
  await ensureParentDir(filePath);
  await fs.writeFile(filePath, `${JSON.stringify(value, null, 2)}\n`, 'utf8');
}

async function writeOverridesTs(entries) {
  const lines = [
    'export interface AssetOverride {',
    '  key: string;',
    '  path: string;',
    '  packageSlug?: string;',
    '  sourceUrl?: string;',
    '  license?: string;',
    '  attribution?: string;',
    '}',
    '',
    '// Generated by scripts/itch_assets.mjs',
    'export const ASSET_OVERRIDES: AssetOverride[] = [',
  ];

  for (const entry of entries) {
    lines.push('  {');
    lines.push(`    key: ${JSON.stringify(entry.key)},`);
    lines.push(`    path: ${JSON.stringify(entry.path)},`);
    if (entry.packageSlug) lines.push(`    packageSlug: ${JSON.stringify(entry.packageSlug)},`);
    if (entry.sourceUrl) lines.push(`    sourceUrl: ${JSON.stringify(entry.sourceUrl)},`);
    if (entry.license) lines.push(`    license: ${JSON.stringify(entry.license)},`);
    if (entry.attribution) lines.push(`    attribution: ${JSON.stringify(entry.attribution)},`);
    lines.push('  },');
  }

  lines.push('];');
  lines.push('');
  await ensureParentDir(OVERRIDES_TS_PATH);
  await fs.writeFile(OVERRIDES_TS_PATH, lines.join('\n'), 'utf8');
}

async function discover(args) {
  const feedUrl = args.url || 'https://itch.io/game-assets/free.xml';
  const output = args.output || CATALOG_PATH;
  const response = await fetch(feedUrl);
  if (!response.ok) {
    throw new Error(`拉取失败: ${response.status} ${response.statusText}`);
  }
  const xml = await response.text();
  const itemRegex = /<item>([\s\S]*?)<\/item>/gi;
  const items = [];
  let match = itemRegex.exec(xml);
  while (match) {
    const itemXml = match[1];
    items.push({
      title: readTag(itemXml, 'title'),
      link: readTag(itemXml, 'link'),
      pubDate: readTag(itemXml, 'pubDate'),
      creator: readTag(itemXml, 'dc:creator'),
      category: readTag(itemXml, 'category'),
      description: readTag(itemXml, 'description'),
    });
    match = itemRegex.exec(xml);
  }

  await writeJson(output, {
    source: feedUrl,
    fetchedAt: new Date().toISOString(),
    count: items.length,
    items,
  });
  console.log(`discover 完成: ${items.length} 条 -> ${output}`);
}

async function ingest(args) {
  const fromDir = args.from;
  const slug = toSafeSlug(args.slug || '');
  const mapArg = args.map;

  if (!fromDir) throw new Error('缺少 --from，本地素材目录路径必填');
  if (!slug) throw new Error('缺少 --slug，示例: --slug neon-city-pack');
  if (!mapArg) throw new Error('缺少 --map，示例: --map player=hero.png,zombie=zombie.png');
  if (!existsSync(fromDir)) throw new Error(`目录不存在: ${fromDir}`);

  const mappings = parseMap(mapArg);
  const allowProtected = String(args['allow-protected'] ?? '').toLowerCase() === 'true';
  if (!allowProtected) {
    const blocked = mappings.filter((mapping) => PROTECTED_KEYS.has(mapping.key));
    if (blocked.length > 0) {
      const keys = blocked.map((item) => item.key).join(', ');
      throw new Error(
        `以下核心贴图默认禁止覆盖: ${keys}。如确认要覆盖，请追加 --allow-protected true`
      );
    }
  }
  const packageDir = path.join(PUBLIC_THIRD_PARTY_DIR, slug);
  await fs.mkdir(packageDir, { recursive: true });

  const overrides = await readJson(OVERRIDES_JSON_PATH, []);
  const attributions = await readJson(ATTRIBUTION_JSON_PATH, []);
  const sourceUrl = typeof args.source === 'string' ? args.source.trim() : '';
  const license = typeof args.license === 'string' ? args.license.trim() : '';
  const attribution = typeof args.attribution === 'string' ? args.attribution.trim() : '';

  const copiedFiles = [];
  for (const mapping of mappings) {
    const sourcePath = path.resolve(fromDir, mapping.relativePath);
    if (!existsSync(sourcePath)) {
      throw new Error(`素材文件不存在: ${sourcePath}`);
    }
    const originalName = path.basename(mapping.relativePath);
    const ext = path.extname(originalName);
    const base = path.basename(originalName, ext);
    const safeName = `${toSafeSlug(base) || 'asset'}${ext.toLowerCase()}`;
    const targetPath = path.join(packageDir, safeName);
    await fs.copyFile(sourcePath, targetPath);

    const webPath = `/${toPosix(path.relative(path.join(ROOT, 'public'), targetPath))}`;
    copiedFiles.push({ key: mapping.key, path: webPath, file: safeName });
  }

  const overrideMap = new Map();
  for (const oldEntry of overrides) {
    if (!oldEntry?.key) continue;
    overrideMap.set(oldEntry.key, oldEntry);
  }
  for (const file of copiedFiles) {
    overrideMap.set(file.key, {
      key: file.key,
      path: file.path,
      packageSlug: slug,
      sourceUrl,
      license,
      attribution,
    });
  }
  const newOverrides = [...overrideMap.values()].sort((a, b) => a.key.localeCompare(b.key));
  await writeJson(OVERRIDES_JSON_PATH, newOverrides);
  await writeOverridesTs(newOverrides);

  const filteredAttributions = attributions.filter((a) => a?.slug !== slug);
  filteredAttributions.push({
    slug,
    importedAt: new Date().toISOString(),
    sourceUrl,
    license,
    attribution,
    files: copiedFiles,
  });
  filteredAttributions.sort((a, b) => String(a.slug).localeCompare(String(b.slug)));
  await writeJson(ATTRIBUTION_JSON_PATH, filteredAttributions);

  console.log(`ingest 完成: ${slug} -> ${copiedFiles.length} 个素材`);
  console.log(`已更新: ${OVERRIDES_TS_PATH}`);
}

async function initFiles() {
  await writeJson(OVERRIDES_JSON_PATH, []);
  await writeJson(ATTRIBUTION_JSON_PATH, []);
  await writeOverridesTs([]);
  await fs.mkdir(PUBLIC_THIRD_PARTY_DIR, { recursive: true });
  console.log('初始化完成: assets/itch + public/assets/third_party');
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const command = args._[0];
  if (!command || command === 'help') {
    console.log(
      [
        '用法:',
        '  node scripts/itch_assets.mjs init',
        '  node scripts/itch_assets.mjs discover [--url https://itch.io/game-assets/free.xml] [--output assets/itch/free-game-assets.json]',
        '  node scripts/itch_assets.mjs ingest --slug pack-name --from /local/folder --map "player=hero.png,zombie=zombie.png"',
        '    [--source https://itch.io/... ] [--license "CC-BY 4.0"] [--attribution "Author Name"]',
        '    [--allow-protected true]  // 默认禁止覆盖角色与地表核心贴图',
      ].join('\n')
    );
    return;
  }

  if (command === 'init') {
    await initFiles();
    return;
  }
  if (command === 'discover') {
    await discover(args);
    return;
  }
  if (command === 'ingest') {
    await ingest(args);
    return;
  }

  throw new Error(`未知命令: ${command}`);
}

main().catch((error) => {
  console.error(`[itch-assets] ${error.message}`);
  process.exit(1);
});
